export const WHITEPAPER = {
  title: 'Official Whitepaper',
  subtitle: 'Understanding the Platform',
  tagline: 'A M. Peters Group Initiative',
  sections: [
    {
      id: 'what-is-reclaim',
      heading: 'What is ReClaim?',
      paragraphs: [
        'There is a plague — quiet, invisible, and deeply personal. It has no fever, no rash, no visible scar. Yet it hollows people out from the inside. It steals focus, corrodes relationships, drains confidence, and leaves its host trapped in a cycle of shame they cannot seem to break. That plague has a name: pornography addiction and compulsive masturbation.',
        'For decades — and with accelerating ferocity in the age of smartphones and high-speed internet — this sexual beast has tormented minds, mostly young ones, with an iron grip. Every year, access to explicit, hyper-stimulating content becomes cheaper, faster, and harder to avoid. What once required effort now arrives in seconds, uninvited, on the very devices we carry everywhere. The ease of access is the trap. And millions have fallen into it.',
        'The world has not been silent. Articles have been written. Videos have been made. Therapists have spoken. Support groups have formed. And yet — the weight of this addiction keeps growing, keeps spreading, keeps winning. Why? Because knowledge alone does not create change. Reading about a battle is not the same as having someone fight it with you.',
        'That is the gap. And that gap is exactly where the devil wins.',
        'ReClaim was created by M. Peters Group to close that gap permanently. ReClaim is not an article. It is not a video. It is not a one-time read that you close and forget. ReClaim is a living, breathing society — a digital companion built for people who are serious about reclaiming full control of their sexual lives.',
        'Think of it as a therapist who never clocks out. A coach who is in the trenches with you — not just on session days, but every second, every minute, every hour of the day. ReClaim tracks your progress in real time. It listens. It responds. It flags your danger zones. It celebrates your victories. It picks you up when you fall. And it keeps feeding you the data, the feedback, and the encouragement you need to keep going — until the chains break for good.',
        'Second by second. Minute by minute. Day by day. Until you are free — not just from the habit, but from the shame, the secrecy, and the cycle. Until you stand in full ownership of who you are and how you live. That is what ReClaim is. That is what ReClaim does. And that is why it exists.',
      ],
    },
    {
      id: 'why-we-built-this',
      heading: 'Why We Built This',
      paragraphs: [
        'Pornography addiction and compulsive masturbation are not niche problems. They are a global crisis — one that quietly dismantles the mental health, confidence, and relationships of millions, yet rarely gets the direct, honest attention it deserves.',
        'Research consistently demonstrates that behavioural change is significantly more effective when supported by real-time, interactive accountability rather than passive, one-way communication. The difference between reading a self-help article and having a system that actively engages with you — tracking your patterns, responding to your triggers, and providing immediate feedback — is the difference between information and transformation.',
        'Traditional recovery resources — books, videos, articles, even periodic therapy sessions — operate on a broadcast model: a message is sent, received once, and then left entirely to the individual to act upon. ReClaim was built to break that model. We exist because the gap between knowing what to do and actually doing it, in real time, in the heat of the moment, is where recovery is either won or lost.',
        'We built ReClaim to live in that gap — and win it with you.',
      ],
    },
    {
      id: 'who-is-this-for',
      heading: 'Who Is This For?',
      paragraphs: [
        'The uncomfortable truth is that exposure to sexual content is happening earlier than most parents or institutions are prepared to address. Studies show that the average age of first exposure to online pornography is between 10 and 12 years old — and for many, that first encounter is the beginning of a habit that follows them through adolescence, young adulthood, and well into their 30s, 40s, and beyond.',
        'ReClaim is for anyone across that entire spectrum. The teenager who stumbled onto something they did not ask for and cannot seem to stop revisiting. The young adult who has tried to quit dozens of times and keeps falling back. The grown man or woman in their 30s or 40s who has carried this in secret for years, too ashamed to tell a partner, a friend, or a therapist.',
        'This is for the person who has spent days, months, and years fighting this battle — and losing. Who has made promises to themselves at night and broken them by morning. Who is exhausted by the cycle and ready — truly ready — for something different.',
        'If you have ever felt that this habit is quietly running your life — affecting your focus, your relationships, your self-image, your confidence — then ReClaim was built for you. This is not a second chance. This is a new one. A real one. And it starts the moment you decide to take it.',
      ],
    },
    {
      id: 'how-it-works',
      heading: 'How ReClaim Works',
      paragraphs: [
        'ReClaim did not happen overnight. What you are using today is the product of over five years of dedicated study, research, and real-world survey — a deep dive into the psychology of addiction, the neuroscience of compulsive behaviour, and most importantly, the lived experiences of the people fighting these battles every day.',
        'Armed with that foundation, the M. Peters Group team built something that has never existed before: a first-of-its-kind interactive recovery model that consolidates every proven method of fighting pornography addiction and compulsive masturbation into a single, unified, progressive dashboard.',
        'At the core of how ReClaim works is a simple but powerful insight — that addiction is not random. It follows patterns. It has triggers. It has cues. Specific emotions, environments, times of day, and states of mind that reliably precede a relapse. Most people never identify these patterns because they are never shown how to look. ReClaim changes that.',
        'From your very first day, ReClaim begins building a picture of your personal triggers and behavioural cues through your daily check-ins and interactions. Over time, that picture becomes sharper. The system learns what puts you at risk — and meets you there with countermeasures that have been proven to work for thousands of people across different backgrounds, ages, and circumstances around the world.',
        'This is not a single method dressed up in new packaging. Every credible, evidence-backed strategy for breaking compulsive sexual behaviour has been studied, tested, and integrated into the ReClaim system — from cognitive behavioural techniques to urge-surfing, pattern interruption, accountability frameworks, and milestone-based motivation. The goal was never to pick one approach and hope it works for everyone. The goal was to bring all of them to you, and walk you through each one, day by day, at exactly the moment you need it.',
        'You do not need to understand the science. You do not need to research the methods. You do not need to figure out what works for you on your own. ReClaim does that work — and then it shows up with you, every single day, until you no longer need it.',
        'Becca is your emotional support companion on this journey — available when you need someone in the moment. Every response is built from your specific triggers and patterns, analysed over time. Nobody else gets your advice. It is yours alone.',
        'For users who choose to opt in, ReClaim also delivers a steady stream of curated support material — newsletters written by recovery specialists, video links covering the psychology and neuroscience of addiction in plain language, and medical talks from professionals who discuss pornography and compulsive masturbation with the clinical honesty the topic deserves. Nothing is pushed on anyone. Everything is permission-based.',
      ],
    },
    {
      id: 'privacy',
      heading: 'Your Privacy and Anonymity',
      paragraphs: [
        'We understand that this is one of the most private battles a person can fight. Shame, secrecy, and fear of judgment are part of what makes addiction to pornography and compulsive masturbation so difficult to address — and we have designed ReClaim with that reality at the centre of every decision.',
        'You are never required to reveal your identity on ReClaim. You may choose to create a full account using your name, age, and email — or you may use ReClaim entirely anonymously, identified only by a name you choose for yourself. Either way, your experience on the platform is identical. Your data is your own.',
        'We do not sell your information. We do not share your journey with third parties. We do not display your progress publicly without your explicit opt-in. What happens on ReClaim stays on ReClaim — because healing requires safety, and safety requires trust.',
        'For users who choose to sign up with an email, your credentials are encrypted and stored securely. For anonymous users, your session data is stored locally on your device — meaning not even our servers hold information that could identify you.',
        'You are not a data point here. You are a person trying to do something hard and brave. We treat you accordingly.',
        'You may export your full journey data at any time from Settings. Account deletion is available on request by contacting reclaimhello@gmail.com.',
      ],
    },
    {
      id: 'sustainability',
      heading: 'Sustainability & Our Promise to You',
      paragraphs: [
        'ReClaim is not free to run. Secure servers, companion support, ongoing development, and the team that maintains this recovery environment all cost real money. That is why we are honest about sustainability instead of pretending the platform can exist on goodwill alone.',
        'Core recovery tools — daily check-ins, pattern tracking, the urge toolkit, milestones, and your Resilience Index — remain available to every member. We do not lock the basic journey behind a wall. What we cannot do is pretend that depth of companion access and advanced reports cost nothing.',
        'We do not run advertisements. Your recovery environment will never be interrupted by commercial content, and there will never be sexual or triggering advertisements on ReClaim. Ever. This is non-negotiable.',
        'Supporter memberships and voluntary donations keep ReClaim operational, improve its features, and expand its reach to more people fighting the same battle around the world. Every contribution goes directly toward sustaining the platform — nothing more, nothing less.',
        'At significant milestones in your recovery journey, ReClaim may gently invite you to support the platform if you are able and willing. This is never compulsory. It will never be a condition of continuing to use ReClaim. It is simply an invitation: if this platform has helped you, consider helping it reach someone else who needs it just as much as you did.',
        'We give every user the power to hold us accountable. Questions, feedback, or concerns can be sent directly to reclaimhello@gmail.com. Your recovery environment is sacred to us, and we will defend it.',
      ],
    },
    {
      id: 'membership',
      heading: 'Membership Tiers',
      paragraphs: [
        'ReClaim offers two paths: Free Member and Supporter Member. Both include the full recovery framework. The difference is in depth of companion access and advanced insights.',
      ],
      tiers: [
        {
          name: 'Free Member',
          price: '$0',
          features: [
            'Daily check-ins and 30-day journey tracker',
            'Confidence Level and Brain Rewiring Index',
            'Resilience Index (RI) with full breakdown',
            'Urge toolkit and emergency protocols',
            'Pattern insights after 30 days of check-ins',
            'Optional leaderboard (opt-in at Day 30)',
            'Milestone celebrations and medal ladder',
          ],
          limitations: [
            'Becca companion: limited daily conversations',
            'Trigger analysis reports: summary only',
            'Export: basic journey report',
          ],
        },
        {
          name: 'Supporter Member',
          price: '$7/month or $70/year',
          features: [
            'Everything in Free Member',
            'Unlimited Becca conversations — anytime you need her',
            'Full personalised trigger analysis reports',
            'Priority pattern insights and weekly summaries',
            'Premium export reports with detailed breakdowns',
            'Early access to new recovery tools',
            'Direct line to the ReClaim team',
          ],
          limitations: [],
        },
      ],
    },
    {
      id: 'milestones',
      heading: 'Milestones and Achievement System',
      paragraphs: [
        'Recovery is not a straight line — but every step forward deserves to be acknowledged. ReClaim\'s milestone and achievement system is built around the belief that progress, however small, is worth celebrating. Because in a battle this personal, momentum is everything.',
        'Achievement points are earned at every level — daily, weekly, and monthly. Each day you check in is a point. Each week you hold your streak is a milestone. Each month you cross is a victory lap. These are not arbitrary badges. They are a running record of every decision you made to show up, even on the hard days — especially on the hard days.',
        'Your daily check-in is your calendar. Every win marked. Every stumble noted without judgment — because a relapse logged is a pattern identified, and a pattern identified is a battle half won. Over time, your check-in history becomes one of the most powerful tools in your recovery: an honest, visual record of how far you have actually come.',
        'ReClaim tracks two deeply personal metrics that most recovery tools ignore entirely. The first is your Confidence Level — rated and tracked over time, so you can see in real terms how your sense of self is rebuilding as the habit loses its grip. The second is your Brain Rewiring Index — a percentage indicator, grounded in neuroscience, that reflects the progressive restoration of healthy dopamine patterns as your recovery advances. Watching that number climb is one of the most motivating experiences on the platform.',
        'For those who want it, ReClaim also offers optional community rankings — a leaderboard of recovery streaks and achievement points shared among users who choose to participate. This is never compulsory. Your journey is private by default. But for those who draw strength from knowing they are not alone — that somewhere out there, thousands of others are fighting the same fight and winning — the rankings exist as a reminder: you are part of something bigger than yourself.',
        'Newsletters are available for users who opt in — sent at a frequency of your choosing, carrying check-in summaries, recovery insights, trigger analysis, and words of encouragement calibrated to exactly where you are in your journey. Nothing lands in your inbox without your permission.',
      ],
    },
    {
      id: 'about',
      heading: 'About M. Peters Group',
      paragraphs: [
        'M. Peters Group was not founded in a boardroom. It was not built by people who read about this problem in a research paper and decided to solve it from a distance. The team behind M. Peters Group are, first and foremost, people who have been there.',
        'They have sat in the same darkness. Fought the same battles. Made the same promises to themselves and broken them. They know what it feels like to be trapped in a cycle that nobody around you knows about — and they know what it feels like to finally break free. That experience is not background context. It is the entire foundation of everything M. Peters Group builds.',
        'The group was formed with one driving conviction: that the people best positioned to help others through a struggle are those who have walked through it themselves, come out the other side, and refused to stay silent about what worked. M. Peters Group exists to turn hard-won personal victories into tools that the world can actually use.',
        'ReClaim is the group\'s flagship initiative — and the most personal one. It carries the weight of every member\'s story, and the genuine, unshakeable belief that freedom from this addiction is not only possible, but available to anyone willing to reach for it.',
      ],
    },
    {
      id: 'final-word',
      heading: 'A Final Word',
      paragraphs: [
        'If you have read this far, something brought you here. Maybe it was curiosity. Maybe it was desperation. Maybe it was a quiet moment of honesty with yourself that you have been putting off for a long time. Whatever it was — we are glad you are here.',
        'We will not dress this up. What you are trying to do is hard. It has been hard every time you have tried before, and it will have hard moments this time too. We are not going to promise you that ReClaim makes it easy. We are going to promise you something better: that this time, you will not be doing it alone.',
        'Every single feature on this platform — every check-in, every milestone, every piece of feedback, every number you watch climb — was designed with one person in mind. Someone exactly like you. Someone who is tired of losing and ready to win. Someone who deserves better than the cycle they are in, and knows it.',
        'Your sexuality is yours. It was never meant to be a source of shame, compulsion, or chaos. It was meant to be something you own — fully, freely, and on your own terms. That is what ReClaim is here to help you get back.',
        'So take the step. Start the journey. And know that from this moment — you are not alone.',
      ],
    },
    {
      id: 'terms',
      heading: 'Terms of Use & Privacy Policy',
      paragraphs: [
        'By using ReClaim, you agree to use the platform for personal recovery support. ReClaim and Becca are recovery companions — not licensed therapy, medical treatment, or crisis intervention.',
        'If you are in immediate danger or experiencing a life-threatening crisis, contact your local emergency services. Use the Emergency urge toolkit for compulsive urges, not for life-threatening emergencies.',
        'You agree not to misuse the platform, harass other users, or attempt to extract internal system content. Your check-in data belongs to you. We store it securely and never sell it.',
        'Anonymous users: data is stored locally on your device. Account users: data syncs to secure cloud storage tied to your account. You may export or request deletion of your data at any time.',
        'Free Member privileges: daily check-ins, the 30-day journey tracker, Confidence Level and Brain Rewiring Index, Resilience Index with full breakdown, the urge toolkit, pattern insights after 30 days, optional leaderboard at Day 30, and the medal ladder. Free Member restrictions: limited Becca conversations, summary-only trigger reports, and a basic journey export.',
        'Supporter Member privileges: everything in Free Member, plus unlimited time with Becca, full personalised trigger analysis reports after 30 days, priority pattern insights, premium export reports, early access to new tools, and a direct line to the ReClaim team. Membership fees support platform operations. Cancellation is available at any time. Refunds are handled on a case-by-case basis via reclaimhello@gmail.com.',
        'We may update this document as the platform evolves. Continued use constitutes acceptance of the current version. Last updated: August 2026.',
      ],
    },
  ],
};
